name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Project build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install & build
        run: |
          yarn install
          yarn build

  docker-build-push:
    needs: [build]
    runs-on: ubuntu-latest
    name: Docker build & push
    steps:
      - name: login in docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: gotoo123/name
          - name: Build & push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              label: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [docker-build-push]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull gotoo123/name:main
